version: "3"

services:
  s1:
    build: 
      context: ./service1
      dockerfile: Dockerfile
    volumes:
      - ./service1:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  s2:
    build: 
      context: ./service2
      dockerfile: Dockerfile
    volumes:
      - ./service2:/app
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - s1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
